register:
    path: /api/v1/register
    controller: App\Controller\AuthController::register
    methods: [POST]

api:
    path: /api/v1/current
    controller: App\Controller\AuthController::api

login_check:
    path: /api/v1/auth
    methods:  [POST]
    
refresh:
    path: /api/v1/token/refresh
    controller: App\Controller\AuthController::refresh
    methods: [POST,GET]
    
pay:
    path: /api/v1/courses/{code}/pay
    controller: App\Controller\TransactionController::doPayment
    methods: [POST]
    
deposite:
    path: /api/v1/deposite/{sum}
    controller: App\Controller\TransactionController::doDeposite
    methods: [POST]    
    
course:
    path: /api/v1/courses/{code}
    controller: App\Controller\TransactionController::showCourse
    methods: [GET]
    
editcourse:
    path: /api/v1/courses/{code}
    controller: App\Controller\AdminUtilsController::editCourse
    methods: [POST]    
        
courses:
    path: /api/v1/courses
    controller: App\Controller\TransactionController::courseList
    methods: [GET]
    
newcourse:
    path: /api/v1/courses
    controller: App\Controller\AdminUtilsController::createCourseByAdmin
    methods: [POST]    
    
transactions:
    path: /api/v1/transactions
    controller: App\Controller\TransactionController::showTransactions
    methods: [GET]    

        
app.swagger_ui:
    path: /api/v1/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
main:
    path: /
    methods: [GET]
    controller: App\Controller\AuthController::main

