register:
    path: /api/v1/register
    controller: App\Controller\AuthController::register
    methods: [POST]

api:
    path: /api
    controller: App\Controller\AuthController::api

login_check:
    path: /api/v1/auth
    methods:  [POST]
refresh:
    path: /api/v1/token/refresh
    controller: App\Controller\AuthController::refresh
    methods: [POST]
    
pay:
    path: /api/v1/courses/{code}/pay
    controller: App\Controller\AuthController::doPayment
    methods: [POST]
    
course:
    path: /api/v1/courses/{code}
    controller: App\Controller\AuthController::showCourse
    methods: [GET]
        
courses:
    path: /api/v1/courses
    controller: App\Controller\AuthController::courseList
    methods: [GET]
    
transactions:
    path: /api/v1/transactions
    controller: App\Controller\AuthController::showTransactions
    methods: [GET]    

        
app.swagger_ui:
    path: /api/doc
    methods: [GET]
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }
main:
    path: /
    methods: [GET]
    controller: App\Controller\AuthController::main

