<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerJ4NX4YT\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerJ4NX4YT/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerJ4NX4YT.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerJ4NX4YT\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerJ4NX4YT\App_KernelDevDebugContainer([
    'container.build_hash' => 'J4NX4YT',
    'container.build_id' => '54339815',
    'container.build_time' => 1622011871,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerJ4NX4YT');
