<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerUVGSX4H\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerUVGSX4H/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerUVGSX4H.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerUVGSX4H\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerUVGSX4H\App_KernelDevDebugContainer([
    'container.build_hash' => 'UVGSX4H',
    'container.build_id' => '1223f625',
    'container.build_time' => 1623064060,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerUVGSX4H');
