<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerNhsfIdt\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerNhsfIdt/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerNhsfIdt.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerNhsfIdt\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerNhsfIdt\App_KernelDevDebugContainer([
    'container.build_hash' => 'NhsfIdt',
    'container.build_id' => '50355c90',
    'container.build_time' => 1621429006,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerNhsfIdt');
