<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    '_wdt' => [['token'], ['_controller' => 'web_profiler.controller.profiler::toolbarAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_wdt']], [], []],
    '_profiler_home' => [[], ['_controller' => 'web_profiler.controller.profiler::homeAction'], [], [['text', '/_profiler/']], [], []],
    '_profiler_search' => [[], ['_controller' => 'web_profiler.controller.profiler::searchAction'], [], [['text', '/_profiler/search']], [], []],
    '_profiler_search_bar' => [[], ['_controller' => 'web_profiler.controller.profiler::searchBarAction'], [], [['text', '/_profiler/search_bar']], [], []],
    '_profiler_phpinfo' => [[], ['_controller' => 'web_profiler.controller.profiler::phpinfoAction'], [], [['text', '/_profiler/phpinfo']], [], []],
    '_profiler_search_results' => [['token'], ['_controller' => 'web_profiler.controller.profiler::searchResultsAction'], [], [['text', '/search/results'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_open_file' => [[], ['_controller' => 'web_profiler.controller.profiler::openAction'], [], [['text', '/_profiler/open']], [], []],
    '_profiler' => [['token'], ['_controller' => 'web_profiler.controller.profiler::panelAction'], [], [['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_router' => [['token'], ['_controller' => 'web_profiler.controller.router::panelAction'], [], [['text', '/router'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::body'], [], [['text', '/exception'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    '_profiler_exception_css' => [['token'], ['_controller' => 'web_profiler.controller.exception_panel::stylesheet'], [], [['text', '/exception.css'], ['variable', '/', '[^/]++', 'token', true], ['text', '/_profiler']], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/api/v1/register']], [], []],
    'api' => [[], ['_controller' => 'App\\Controller\\AuthController::api'], [], [['text', '/api/v1/current']], [], []],
    'login_check' => [[], [], [], [['text', '/api/v1/auth']], [], []],
    'refresh' => [[], ['_controller' => 'App\\Controller\\AuthController::refresh'], [], [['text', '/api/v1/token/refresh']], [], []],
    'pay' => [['code'], ['_controller' => 'App\\Controller\\TransactionController::doPayment'], [], [['text', '/pay'], ['variable', '/', '[^/]++', 'code', true], ['text', '/api/v1/courses']], [], []],
    'deposite' => [['sum'], ['_controller' => 'App\\Controller\\TransactionController::doDeposite'], [], [['variable', '/', '[^/]++', 'sum', true], ['text', '/api/v1/deposite']], [], []],
    'course' => [['code'], ['_controller' => 'App\\Controller\\TransactionController::showCourse'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/v1/courses']], [], []],
    'editcourse' => [['code'], ['_controller' => 'App\\Controller\\AdminUtilsController::editCourse'], [], [['variable', '/', '[^/]++', 'code', true], ['text', '/api/v1/courses']], [], []],
    'courses' => [[], ['_controller' => 'App\\Controller\\TransactionController::courseList'], [], [['text', '/api/v1/courses']], [], []],
    'newcourse' => [[], ['_controller' => 'App\\Controller\\AdminUtilsController::createCourseByAdmin'], [], [['text', '/api/v1/courses']], [], []],
    'transactions' => [[], ['_controller' => 'App\\Controller\\TransactionController::showTransactions'], [], [['text', '/api/v1/transactions']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/v1/doc']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\AuthController::main'], [], [['text', '/']], [], []],
];
