<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    '_preview_error' => [['code', '_format'], ['_controller' => 'error_controller::preview', '_format' => 'html'], ['code' => '\\d+'], [['variable', '.', '[^/]++', '_format', true], ['variable', '/', '\\d+', 'code', true], ['text', '/_error']], [], []],
    'app.swagger' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger'], [], [['text', '/api/doc.json']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\AuthController::register'], [], [['text', '/register']], [], []],
    'api' => [[], ['_controller' => 'App\\Controller\\AuthController::api'], [], [['text', '/api']], [], []],
    'login_check' => [[], [], [], [['text', '/api/v1/auth']], [], []],
    'app.swagger_ui' => [[], ['_controller' => 'nelmio_api_doc.controller.swagger_ui'], [], [['text', '/api/doc']], [], []],
    'main' => [[], ['_controller' => 'App\\Controller\\AuthController::main'], [], [['text', '/']], [], []],
];
